artifacts:
  - name: "@daiyam/artifact-lang-js"
    version: 0.5.0
  - name: "@daiyam/artifact-lang-ts"
    version: 0.4.0
  - name: "@daiyam/artifact-npm-ts"
    version: 0.2.0
  - name: "@daiyam/artifact-npm-cli-ts"
    version: 0.2.0
  - name: "@daiyam/artifact-npm-zokugun"
    version: 0.1.0
